# database.py — compatibility shim
# All logic has been moved to the db/ package (domain-driven modules).
# This file re-exports every public symbol so that existing imports in
# main.py and other callers continue to work without modification.

from .db.connection import (
    SafeConnectionWrapper,
    SafeCursorWrapper,
    get_db_conn,
    init_db_v2,
)
from .db.situation_db import (
    save_situation,
    get_situation_history,
)
from .db.session_db import (
    # session CRUD
    save_session,
    get_session,
    get_session_by_id,
    get_active_session,
    get_all_active_sessions,
    update_session_status,
    update_session_device_id,
    close_session_and_archive,
    # orders (moved from order_db)
    append_order,
    save_order,
    get_orders_by_session,
    update_order_items,
    update_order_status,
    update_order_payment_status,
    update_order_payment_key,
    get_order_by_id,
    get_max_order_seq,
    get_kitchen_orders,
    get_all_active_orders_as_bundles,
    get_ready_orders,
    get_next_display_number,
    # calls (moved from operations_db)
    append_call,
    save_call,
    get_active_calls,
    update_call_status,
    update_call_in_session,
    # parking (moved from operations_db)
    set_parking,
    save_parking,
    complete_parking,
    get_parking_by_session,
    get_active_parkings_db,
    update_parking_status,
    # point
    set_point,
    get_point,
    # splits (Dutch pay)
    append_split,
    update_split_status,
    get_splits,
    init_dutch_splits,
    add_dutch_payment,
)
from .db.staff_db import (
    save_staff,
    get_staff,
    get_active_staff_list,
    update_staff_status,
    save_schedule,
    get_staff_schedules,
    get_all_staff_as_bundles,
)
from .db.attendance_db import (
    save_attendance_checkin,
    get_today_checkin,
    save_attendance_checkout,
    get_today_checkout,
    get_active_attendance_log,
    get_staff_attendance_logs,
    get_all_attendance_as_bundles,
    get_recent_device_scan,
)
from .db.operations_db import (
    save_waiting,
    get_active_waitings,
    update_waiting_status,
    save_reservation,
    get_active_reservations,
    update_reservation_status,
    get_all_reservations,
    update_reservation,
    delete_reservation,
    confirm_reservation_contact,
)
from .db.points_db import (
    get_customer_points,
    update_customer_points,
    use_customer_points,
    get_points_list_db,
)
from .db.store_db import (
    get_stores_db,
    add_store_db,
    update_store_db,
    delete_store_db,
    seed_stores_from_pool,
    get_store_use_kitchen,
    update_store_use_kitchen,
    get_store_use_call,
    update_store_use_call,
    get_store_use_waiting,
    update_store_use_waiting,
    get_store_use_parking,
    update_store_use_parking,
    get_store_use_points,
    update_store_use_points,
    get_store_use_reservation,
    update_store_use_reservation,
    get_store_use_display,
    update_store_use_display,
    get_store_use_staff,
    update_store_use_staff,
    get_store_use_dutch,
    update_store_use_dutch,
    get_reservation_settings,
    update_reservation_settings,
)

__all__ = [
    # connection
    "SafeConnectionWrapper",
    "SafeCursorWrapper",
    "get_db_conn",
    "init_db_v2",
    # situation
    "save_situation",
    "get_situation_history",
    # session
    "save_session",
    "get_session",
    "get_session_by_id",
    "get_active_session",
    "get_all_active_sessions",
    "update_session_status",
    "update_session_device_id",
    "close_session_and_archive",
    # orders
    "append_order",
    "save_order",
    "get_orders_by_session",
    "update_order_items",
    "update_order_status",
    "update_order_payment_status",
    "update_order_payment_key",
    "get_order_by_id",
    "get_max_order_seq",
    "get_kitchen_orders",
    "get_all_active_orders_as_bundles",
    "get_ready_orders",
    "get_next_display_number",
    # calls
    "append_call",
    "save_call",
    "get_active_calls",
    "update_call_status",
    "update_call_in_session",
    # parking
    "set_parking",
    "save_parking",
    "complete_parking",
    "get_parking_by_session",
    "get_active_parkings_db",
    "update_parking_status",
    # point
    "set_point",
    "get_point",
    # splits
    "append_split",
    "update_split_status",
    "get_splits",
    "init_dutch_splits",
    "add_dutch_payment",
    # staff
    "save_staff",
    "get_staff",
    "get_active_staff_list",
    "update_staff_status",
    "save_schedule",
    "get_staff_schedules",
    "get_all_staff_as_bundles",
    # attendance
    "save_attendance_checkin",
    "get_today_checkin",
    "save_attendance_checkout",
    "get_today_checkout",
    "get_active_attendance_log",
    "get_staff_attendance_logs",
    "get_all_attendance_as_bundles",
    "get_recent_device_scan",
    # operations (waiting / reservation)
    "save_waiting",
    "get_active_waitings",
    "update_waiting_status",
    "save_reservation",
    "get_active_reservations",
    "update_reservation_status",
    "get_all_reservations",
    "update_reservation",
    "delete_reservation",
    "confirm_reservation_contact",
    # points
    "get_customer_points",
    "update_customer_points",
    "use_customer_points",
    "get_points_list_db",
    # store
    "get_stores_db",
    "add_store_db",
    "update_store_db",
    "delete_store_db",
    "seed_stores_from_pool",
    "get_store_use_kitchen",
    "update_store_use_kitchen",
    "get_store_use_call",
    "update_store_use_call",
    "get_store_use_waiting",
    "update_store_use_waiting",
    "get_store_use_parking",
    "update_store_use_parking",
    "get_store_use_points",
    "update_store_use_points",
    "get_store_use_reservation",
    "update_store_use_reservation",
    "get_store_use_display",
    "update_store_use_display",
    "get_store_use_staff",
    "update_store_use_staff",
    "get_store_use_dutch",
    "update_store_use_dutch",
    "get_reservation_settings",
    "update_reservation_settings",
]
